
"use client";

import React from 'react';
import { GlassCard } from '../components/GlassCard';
import { Download, BookOpen, Palette, Type, Layout, MousePointer2 } from 'lucide-react';

export const DevSpecsSection: React.FC = () => {
  const isLight = typeof document !== 'undefined' && document.body.classList.contains('light-mode');

  const downloadDoc = () => {
    const docContent = `# ADGRADNIS Nebula - Design System Documentation

## 1. Core Color Palette
- Primary Base: #FFFFFF (Light) / #050505 (Dark)
- Guardian Cyan: #0EA5E9 (Light) / #00F2EA (Dark)
- Neon Pink: #FE2C55 (Light) / #FF0050 (Dark)

## 2. Component Styling Specs
- Glass Cards: Backrop blur 12px, 1px soft border.
- Shadow Depth: Cyan-tinted shadows (Emerald Glow).
- Interactions: 200ms transitions, translateY(-4px) hover effect.

## 3. Typography
- Titles: Plus Jakarta Sans, font-black, italic, uppercase.
- Metric Numbers: Prominent size, high contrast.
- Labels: Small, muted, tracking-widest.

---
Generated by ADGRADNIS Nebula Tactical Interface.`;

    const blob = new Blob([docContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'ADGRADNIS_Nebula_Design_Specs.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 pb-24 max-w-5xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <h2 className="text-4xl font-black text-brand-textHigh tracking-tighter uppercase italic leading-none">System Architecture</h2>
          <p className="text-brand-textLow font-medium flex items-center gap-2 mt-2 italic text-sm">
            <BookOpen size={14} className={isLight ? 'text-brand-pink' : 'text-brand-neon'} /> 
            Guardian Design System v1.2 Specifications.
          </p>
        </div>
        <button 
          onClick={downloadDoc}
          className={`px-8 py-4 rounded-2xl font-black text-xs uppercase tracking-widest italic flex items-center gap-3 transition-all active:scale-95 shadow-xl ${isLight ? 'bg-slate-950 text-white hover:bg-slate-800' : 'bg-brand-neon text-brand-dark hover:shadow-brand-neon/20'}`}
        >
          <Download size={18} /> Download Specs (.md)
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <GlassCard className="space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <Palette className={isLight ? 'text-brand-pink' : 'text-brand-neon'} size={24} />
            <h3 className="text-xl font-black italic uppercase">Color Matching</h3>
          </div>
          <p className="text-sm text-brand-textLow leading-relaxed">
            The <strong>Guardian Palette</strong> uses a high-contrast ratio of 14:1. In Light Mode, we use Cyan-to-White gradients to simulate frozen glass.
          </p>
          <div className="grid grid-cols-3 gap-2 mt-4">
            <div className="h-10 rounded-lg bg-[#0EA5E9] border border-white/20" />
            <div className="h-10 rounded-lg bg-[#FE2C55] border border-white/20" />
            <div className="h-10 rounded-lg bg-[#0F172A] border border-white/20" />
          </div>
        </GlassCard>

        <GlassCard className="space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <Type className={isLight ? 'text-brand-pink' : 'text-brand-neon'} size={24} />
            <h3 className="text-xl font-black italic uppercase">Typography</h3>
          </div>
          <p className="text-sm text-brand-textLow leading-relaxed">
            We exclusively use <strong>Plus Jakarta Sans</strong>. All headers must be bold/black and italicized for a high-velocity fintech feel.
          </p>
          <div className="space-y-1">
            <p className="heavy-italic text-2xl uppercase">ADGRADNIS NEBULA</p>
            <p className="label-tracking">System Meta Label</p>
          </div>
        </GlassCard>

        <GlassCard className="space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <Layout className={isLight ? 'text-brand-pink' : 'text-brand-neon'} size={24} />
            <h3 className="text-xl font-black italic uppercase">Grid Density</h3>
          </div>
          <p className="text-sm text-brand-textLow leading-relaxed">
            A tight 12-column grid system with 32px gutters ensures maximum information density for tactical decision making.
          </p>
        </GlassCard>

        <GlassCard className="space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <MousePointer2 className={isLight ? 'text-brand-pink' : 'text-brand-neon'} size={24} />
            <h3 className="text-xl font-black italic uppercase">Interactions</h3>
          </div>
          <p className="text-sm text-brand-textLow leading-relaxed">
            Hover states are strictly 200ms ease-out. Interaction feedback is critical; every active element must scale on click.
          </p>
        </GlassCard>
      </div>

      <GlassCard className="!p-10">
        <h3 className="text-2xl font-black italic uppercase mb-6">Light Mode Match Rules</h3>
        <ul className="space-y-4 text-sm text-brand-textLow font-medium">
          <li className="flex items-start gap-4 italic">
            <div className="w-1.5 h-1.5 rounded-full bg-brand-pink mt-1.5" />
            <span>Don't use pure Black: Always use Slate-900 or Slate-950 for text.</span>
          </li>
          <li className="flex items-start gap-4 italic">
            <div className="w-1.5 h-1.5 rounded-full bg-brand-pink mt-1.5" />
            <span>Shadow Depth: Use cyan-tinted shadows to keep the Nebula identity.</span>
          </li>
          <li className="flex items-start gap-4 italic">
            <div className="w-1.5 h-1.5 rounded-full bg-brand-pink mt-1.5" />
            <span>Whitespace: Light mode requires 15% more padding than dark mode to feel premium.</span>
          </li>
        </ul>
      </GlassCard>
    </div>
  );
};
